name: Publish sbt-docker

on:
  push:
    branches:
      - master
    paths:
      - 'sbt-docker/**'

env:
  IMAGE_NAME: 'grupoabraxas/sbt-docker'
  IMAGE_TAG: 'latest'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG ./sbt-docker

      - name: Docker login
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
